name: Manual Test Runner

on:
  workflow_dispatch:
    # Optional inputs you might want to provide when triggering the workflow
    inputs:
      test_suite:
        description: "Which test suite to run"
        required: false
        default: "all"
        type: choice
        options:
          - all
          - auth
          - tasks
          - notifications

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - run: npm i
      - name: Run all tests
        if: ${{ github.event.inputs.test_suite == 'all' }}
        run: npm run test:isolated
      - name: Run auth tests
        if: ${{ github.event.inputs.test_suite == 'auth' }}
        run: npm run test:auth
      - name: Run task tests
        if: ${{ github.event.inputs.test_suite == 'tasks' }}
        run: npm run test:tasks
      - name: Run notification tests
        if: ${{ github.event.inputs.test_suite == 'notifications' }}
        run: npm run test:notifications
